# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:

  info:
    docker: 
      - image: rocker/tidyverse:3.6.2
    steps:
      - run:
          command: |-
            echo "TRIGGERER: ${CIRCLE_USERNAME}"
            echo "BUILD_NUMBER: ${CIRCLE_BUILD_NUM}"
            echo "BUILD_URL: ${CIRCLE_BUILD_URL}"
            echo "BRANCH: ${CIRCLE_BRANCH}"
            echo "RUNNING JOB: ${CIRCLE_JOB}"
            echo "JOB PARALLELISM: ${CIRCLE_NODE_TOTAL}"
            echo "CIRCLE_REPOSITORY_URL: ${CIRCLE_REPOSITORY_URL}"
          name: Show some of the CircleCI runtime env vars
      - run:
          command: |-
            echo "uname:" $(uname -a)
            echo "arch: " $(arch)
          name: Show system information

  build:
    docker:
      - image: rocker/tidyverse:3.6.2
    steps:
      - checkout:
          path: hello.circleci
      - run:
          name: "build package"
          command: R CMD build hello.circleci
      - run:
          name: "get package build name"
          command: echo "export PKG=$(echo hello.circleci_*.tar.gz)" >> $BASH_ENV
      - persist_to_workspace:
          root: ./
          paths:
            - hello.circleci_0.1.0.tar.gz

  test:
    docker:
      - image: rocker/tidyverse:3.6.2
    steps:
      - attach_workspace:
          at: ./
      - run:
          command: |
            apt install tree 
            tree

  check:
    docker:
      - image: rocker/tidyverse:3.6.2
    steps:
      - run:
          name: "check package"
          command: R CMD check --no-manual --no-build-vignettes ${PKG}
      - run:
          name: "install package"
          command: R CMD INSTALL ${PKG}
      - run:
          name: "create pkgdown website"
          command: R -e 'pkgdown::build_site("hello.circleci", devel = FALSE)'
#      - store_artifacts:
#          path: hello.circleci.Rcheck
#          destination: hello.circleci.Rcheck
#      - store_artifacts:
#          path: hello.circleci/docs
#          destination: pkgdown
#      - store_test_results:
#          path: hello.circleci.Rcheck/tests
workflows:
  version: 2
  test:
    jobs:
      - build
      - test:
          requires:
            - build

